# Ref: https://man.sr.ht/builds.sr.ht/
sources:
  - https://git.sr.ht/~lukeshu/btrfs-ng

image: archlinux
packages:
  - go
  - make
tasks:
  - lint: make -C btrfs-ng lint
  - check: make -C btrfs-ng check
  - generate: |
      cd btrfs-ng
      make generate
      git add .
      if [[ -n "$(git status --porcelain)" ]]; then
        PAGER= git diff --cached
        exit 1
      fi
