# Copyright (C) 2022  Luke Shumaker <lukeshu@lukeshu.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

linters:
  disable:
    - structcheck # doesn't support Go 1.18 yet
  enable:
    - forbidigo
    - gofmt
linters-settings:
  gofmt:
    simplify: true
